_BASE_: "Base-CenterNet2.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 365
  CENTERNET:
    NUM_CLASSES: 365
DATASETS:
  TRAIN: ("objects365_train",)
  TEST: ("objects365_val",)
DATALOADER:
  SAMPLER_TRAIN: "ClassAwareSampler"
  SOURCE_AWARE: True
SOLVER:
  STEPS: (50,)
  MAX_ITER: 100
TEST:
  DETECTIONS_PER_IMAGE: 300
