_BASE_: "Base-CenterNet2.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 732
  CENTERNET:
    NUM_CLASSES: 732
DATASETS:
  TRAIN: ("uni_train_mini",)
  TEST: ("uni_val_mini",)
DATALOADER:
  SAMPLER_TRAIN: "ClassAwareSampler"
  SOURCE_AWARE: True
TEST:
  DETECTIONS_PER_IMAGE: 300